# Generated by Django 6.0.4 on 2026-04-29 11:20

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('location', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_type', models.CharField(choices=[('paid', 'Already Paid'), ('cod_collect', 'COD Collect'), ('cod_shop', 'COD Pay To Shop')], default='paid', max_length=20)),
                ('expected_collect', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('actual_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('lack_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('delivery_fee_paid', models.BooleanField(default=False)),
                ('exchange_rate_note', models.CharField(blank=True, max_length=150)),
                ('delivery_note', models.TextField(blank=True)),
                ('delivery_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('pending', 'Pending / Next Delivery'), ('out', 'Out For Delivery'), ('done', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='deliverystatuslog',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='deliverystatuslog',
            name='changed_by',
        ),
        migrations.DeleteModel(
            name='DeliveryOrder',
        ),
        migrations.DeleteModel(
            name='DeliveryStatusLog',
        ),
    ]
