# Generated by Django 6.0.4 on 2026-04-29 11:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delivery_remove_deliverystatuslog_delivery_and_more'),
        ('inventory', '0008_branch_branchstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery.delivery')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.itemvariant')),
            ],
        ),
    ]
