# Generated by Django 6.0.4 on 2026-05-05 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryitem'),
        ('inventory', '0009_stockmovement_after_quantity_and_more'),
        ('pos', '0008_alter_cashcount_options_cashcount_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='inventory.branch'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery', to='pos.sale'),
        ),
    ]
