# Generated by Django 6.0.4 on 2026-05-10 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_delivery_branch_delivery_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('delivery_type', models.CharField(choices=[('pp', 'Phnom Penh'), ('province', 'Province')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['delivery_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='chat_source',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('call', 'Call'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_area',
            field=models.CharField(choices=[('pp', 'Phnom Penh'), ('province', 'Province')], default='pp', max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='social_name',
            field=models.CharField(blank=True, help_text='Customer Facebook / Telegram / IG / TikTok name', max_length=150),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.deliverycompany'),
        ),
    ]
