# Generated by Django 6.0.4 on 2026-06-30 16:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_delivery_shipper_alter_delivery_social_name'),
        ('inventory', '0012_branch_allowed_radius_meters_branch_latitude_and_more'),
        ('pos', '0013_abapaymentsession_combinedpaymentsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-delivery_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='delivery',
            name='cod_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='cod_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='cod_received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_cod_received_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='cod_settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='cod_settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_cod_settled_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='cod_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('waiting', 'Waiting Money'), ('received', 'Money Received'), ('short', 'Short Money'), ('settled', 'Settled'), ('returned', 'Returned')], default='not_applicable', max_length=30),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_completed_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='return_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='return_stock_restored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delivery',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_return_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverycompany',
            name='default_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default delivery expense used when this company is selected.', max_digits=10),
        ),
        migrations.AddField(
            model_name='deliverycompany',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='payment_type',
            field=models.CharField(choices=[('paid', 'Already Paid'), ('cod_collect', 'COD Collect'), ('cod_shop', 'COD Pay To Shop (Legacy)')], default='paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending / Next Delivery'), ('out', 'Out For Delivery'), ('done', 'Delivered'), ('failed', 'Delivery Failed'), ('returned', 'Returned + Stock Restored'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['delivery_area', 'delivery_company'], name='delivery_de_deliver_600c10_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', 'delivery_date'], name='delivery_de_status_4582e4_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['payment_type', 'cod_status'], name='delivery_de_payment_ba9149_idx'),
        ),
    ]
