# Generated by Django 6.0.4 on 2026-05-04 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'verbose_name': 'Staff Profile', 'verbose_name_plural': 'Staff Profiles'},
        ),
    ]
