# Generated by Django 6.0.4 on 2026-05-05 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petsale',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pet_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petwarrantyclaim',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pet_warranty_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PetVaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_no', models.PositiveIntegerField(default=1)),
                ('vaccine_name', models.CharField(blank=True, default='', help_text='Example: Vaccine 1, Vaccine 2, 5-in-1, Rabies', max_length=120)),
                ('vaccine_date', models.DateField(blank=True, null=True)),
                ('next_recommended_date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pet_vaccines', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='pets.pet')),
            ],
            options={
                'ordering': ['vaccine_no', 'id'],
            },
        ),
    ]
