# Generated by Django 6.0.4 on 2026-05-06 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_death_date_pet_updated_at_alter_pet_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsale',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='petsale',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petsale',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petsale',
            name='preorder_breed',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='petsale',
            name='preorder_gender',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='petsale',
            name='preorder_pet_type',
            field=models.CharField(blank=True, choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], default='dog', max_length=20),
        ),
        migrations.AddField(
            model_name='petsale',
            name='refund_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='petsale',
            name='sale_kind',
            field=models.CharField(choices=[('in_stock', 'In-stock Pet Sale'), ('preorder', 'Pre-order Pet')], default='in_stock', max_length=30),
        ),
        migrations.AddField(
            model_name='petsale',
            name='warranty_days',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='petsale',
            name='warranty_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petsale',
            name='warranty_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petsale',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='pets.pet'),
        ),
        migrations.AlterField(
            model_name='petsale',
            name='status',
            field=models.CharField(choices=[('deposit', 'Deposit / Waiting'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('cancelled', 'Customer Cancelled'), ('refunded', 'Refunded')], default='deposit', max_length=30),
        ),
    ]
