# Generated by Django 6.0.4 on 2026-05-13 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_petsale_cancel_reason_petsale_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age_text',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='pet',
            name='special_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='petsale',
            name='preorder_color',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='petsale',
            name='preorder_special_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='PetBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], default='dog', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pet_breeds/')),
                ('default_cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('default_sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('color_options', models.CharField(blank=True, help_text='Example: White, Cream, Brown, Black', max_length=255)),
                ('sex_options', models.CharField(blank=True, default='Male,Female', help_text='Example: Male, Female', max_length=255)),
                ('special_type_options', models.CharField(blank=True, help_text='Example: Teacup, Mini, Standard, Show Grade', max_length=255)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pet_breeds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pet_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='breed_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='pets.petbreed'),
        ),
    ]
