# Generated by Django 6.0.4 on 2026-05-13 04:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_pet_age_text_pet_special_type_petsale_preorder_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='age_text',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='pet',
            name='age_months_at_stock_in',
            field=models.PositiveIntegerField(default=0, help_text='Age in months when this pet was stocked in.'),
        ),
        migrations.AddField(
            model_name='pet',
            name='age_recorded_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Date when age was recorded.'),
        ),
    ]
