# Generated by Django 6.0.4 on 2026-05-13 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_remove_pet_age_text_remove_pet_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetSalePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='pet_sale_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pets.petsale')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
