# Generated by Django 6.0.4 on 2026-05-13 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_petsalephoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='petsale',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Real seller/staff who sold this pet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet_sales_as_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
