# Generated by Django 6.0.4 on 2026-05-14 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_itemedithistory'),
        ('pets', '0007_petsale_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch/shop this pet is currently stocked in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='inventory.branch'),
        ),
    ]
