# Generated by Django 6.0.4 on 2026-05-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_pet_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
