# Generated by Django 6.0.4 on 2026-07-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_petsale_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsale',
            name='customer_source',
            field=models.CharField(choices=[('walk_in', 'Walk-in'), ('staff_chat', 'Staff Chat'), ('page_chat', 'Page Chat'), ('delivery', 'Delivery'), ('referral', 'Referral')], default='staff_chat', help_text='How the customer contacted the shop, such as chat or walk-in.', max_length=30),
        ),
    ]
