# Generated by Django 6.0.4 on 2026-08-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_petsale_customer_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsale',
            name='warranty_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
