# Generated by Django 6.0.4 on 2026-04-28 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_variantedithistory'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='quantity',
            new_name='ordered_qty',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='item',
        ),
        migrations.AddField(
            model_name='purchase',
            name='shipping_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('partial', 'Partial Received'), ('received', 'Fully Received'), ('cancelled', 'Cancelled')], default='ordered', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='received_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='inventory.itemvariant'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='PurchaseReceiveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_logs', to='purchases.purchaseitem')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
