# Generated by Django 6.0.4 on 2026-04-28 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_branch_branchstock'),
        ('purchases', '0002_rename_quantity_purchaseitem_ordered_qty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBranchAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_allocations', to='inventory.branch')),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_allocations', to='purchases.purchaseitem')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
