# Generated by Django 6.0.4 on 2026-04-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_itemtype_remove_item_category_remove_item_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_variants/'),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=80, unique=True),
        ),
    ]
