# Generated by Django 6.0.4 on 2026-04-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_itemvariant_image_itemvariant_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariant',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
