# Generated by Django 6.0.4 on 2026-04-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_itemvariant_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemvariant',
            options={'ordering': ['item__name', 'size', 'color', 'label', 'id']},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddIndex(
            model_name='itemvariant',
            index=models.Index(fields=['item', 'is_active'], name='inventory_i_item_id_9c2385_idx'),
        ),
        migrations.AddIndex(
            model_name='itemvariant',
            index=models.Index(fields=['sku'], name='inventory_i_sku_6ecdd0_idx'),
        ),
    ]
