# Generated by Django 6.0.4 on 2026-05-04 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_branch_branchstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='after_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='before_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.branch'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjust', 'Adjust Stock'), ('sale', 'Sale'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('damage', 'Damage / Expired / Lost')], max_length=30),
        ),
    ]
