# Generated by Django 6.0.4 on 2026-05-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_stockmovement_after_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(blank=True, default='📏', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('bottle', 'Bottle'), ('ml', 'ML'), ('g', 'Gram'), ('kg', 'KG'), ('pack', 'Pack'), ('box', 'Box'), ('service', 'Service'), ('pet', 'Pet')], default='piece', max_length=20),
        ),
    ]
