# Generated by Django 6.0.4 on 2026-05-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_itemedithistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='allowed_radius_meters',
            field=models.PositiveIntegerField(default=150, help_text='Allowed distance from branch for attendance scan.'),
        ),
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Branch GPS latitude.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Branch GPS longitude.', max_digits=10, null=True),
        ),
    ]
