# Generated by Django 6.0.4 on 2026-07-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_branch_allowed_radius_meters_branch_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemvariant',
            options={'ordering': ['item__name', 'sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='itemvariant',
            index=models.Index(fields=['item', 'sort_order'], name='inventory_i_item_id_ee45d5_idx'),
        ),
    ]
