# Generated by Django 6.0.4 on 2026-07-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_itemvariant_options_itemvariant_sort_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='customer_display_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='branch',
            name='customer_display_payment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='customer_display_payment_event_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='payment_qr_image',
            field=models.ImageField(blank=True, help_text='Upload the payment QR image used by this branch.', null=True, upload_to='branch_payment_qr/'),
        ),
        migrations.AddField(
            model_name='branch',
            name='payment_qr_label',
            field=models.CharField(blank=True, default='Scan to pay', help_text='Text shown below the QR on the customer display.', max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='payment_qr_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
