# Generated by Django 6.0.4 on 2026-07-18 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_branch_customer_display_payment_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCountSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Counting / Draft'), ('review', 'Waiting Confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_sessions', to='inventory.branch')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_stock_counts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_counts', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_stock_counts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.IntegerField(default=0)),
                ('actual_quantity', models.IntegerField(blank=True, null=True)),
                ('reason_code', models.CharField(blank=True, choices=[('missing', 'Missing item'), ('damaged', 'Damaged'), ('expired', 'Expired'), ('found_extra', 'Found extra stock'), ('previous_wrong', 'Previous count was wrong'), ('transfer_unrecorded', 'Transfer was not recorded'), ('other', 'Other')], default='', max_length=30)),
                ('reason_note', models.CharField(blank=True, default='', max_length=255)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('applied_before_quantity', models.IntegerField(blank=True, null=True)),
                ('applied_after_quantity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counted_stock_lines', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_lines', to='inventory.itemvariant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockcountsession')),
            ],
            options={
                'ordering': ['variant_id'],
            },
        ),
        migrations.AddIndex(
            model_name='stockcountsession',
            index=models.Index(fields=['branch', 'status'], name='inventory_s_branch__8719d9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcountsession',
            index=models.Index(fields=['created_at'], name='inventory_s_created_903c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcountline',
            index=models.Index(fields=['session', 'actual_quantity'], name='inventory_s_session_d3b90c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcountline',
            index=models.Index(fields=['variant'], name='inventory_s_variant_d904c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockcountline',
            constraint=models.UniqueConstraint(fields=('session', 'variant'), name='unique_stock_count_session_variant'),
        ),
    ]
