# Generated by Django 6.0.4 on 2026-08-21 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_stockcountsession_stockcountline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_quantity', models.PositiveIntegerField(default=1, help_text='How many child units are inside one parent unit.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_variant', models.ForeignKey(help_text='Smaller unit, e.g. Pill.', on_delete=django.db.models.deletion.PROTECT, related_name='unit_conversion_child_rules', to='inventory.itemvariant')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_unit_conversions', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversions', to='inventory.item')),
                ('parent_variant', models.ForeignKey(help_text='Larger unit, e.g. Box.', on_delete=django.db.models.deletion.PROTECT, related_name='unit_conversion_parent_rules', to='inventory.itemvariant')),
            ],
            options={
                'ordering': ['parent_variant__sort_order', 'parent_variant_id', 'child_variant_id'],
            },
        ),
        migrations.CreateModel(
            name='UnitConversionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_quantity', models.PositiveIntegerField()),
                ('target_quantity', models.PositiveIntegerField()),
                ('source_before_quantity', models.IntegerField(default=0)),
                ('source_after_quantity', models.IntegerField(default=0)),
                ('target_before_quantity', models.IntegerField(default=0)),
                ('target_after_quantity', models.IntegerField(default=0)),
                ('conversion_rate', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_conversion_histories', to='inventory.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_unit_conversion_histories', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_conversion_histories', to='inventory.item')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='histories', to='inventory.itemunitconversion')),
                ('source_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_conversion_source_histories', to='inventory.itemvariant')),
                ('target_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_conversion_target_histories', to='inventory.itemvariant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='itemunitconversion',
            constraint=models.UniqueConstraint(fields=('item', 'parent_variant', 'child_variant'), name='unique_item_parent_child_unit_conversion'),
        ),
        migrations.AddIndex(
            model_name='unitconversionhistory',
            index=models.Index(fields=['branch', 'item', 'created_at'], name='inventory_u_branch__5c63fb_idx'),
        ),
    ]
