# Generated by Django 6.0.4 on 2026-05-14 10:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0012_branch_allowed_radius_meters_branch_latitude_and_more'),
        ('pets', '0008_pet_branch'),
        ('users', '0002_alter_staffprofile_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchAttendanceQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=120, unique=True)),
                ('title', models.CharField(default='Main Attendance QR', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_qrs', to='inventory.branch')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('expected_open_date', models.DateField()),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('late_days', models.PositiveIntegerField(default=0)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('absent_days', models.PositiveIntegerField(default=0)),
                ('permission_days', models.PositiveIntegerField(default=0)),
                ('late_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('absent_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('opened', 'Opened'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_payroll_records', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_payroll_records', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='users.staffprofile')),
            ],
            options={
                'ordering': ['-period_start', 'staff__user__username'],
            },
        ),
        migrations.CreateModel(
            name='PayrollHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('opened', 'Opened'), ('edited', 'Edited'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('commission_added', 'Commission Added'), ('deduction_added', 'Deduction Added'), ('permission_requested', 'Permission Requested'), ('permission_approved', 'Permission Approved'), ('permission_rejected', 'Permission Rejected')], max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_histories', to=settings.AUTH_USER_MODEL)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='staffs.payrollrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('payroll_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='staffs.payrollrecord')),
                ('pet_sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_commission', to='pets.petsale')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_sale_commissions', to='users.staffprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffPayrollSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_work_date', models.DateField(default=django.utils.timezone.localdate)),
                ('salary_cycle_start_day', models.PositiveIntegerField(default=1, help_text='Example: 5 means salary cycle is 5th this month to 4th next month.')),
                ('salary_open_after_days', models.PositiveIntegerField(default=6, help_text='Example: period ends on 4th, open after 6 days = 10th.')),
                ('attendance_pin', models.CharField(blank=True, help_text='PIN staff enters after scanning branch QR.', max_length=20)),
                ('commission_enabled', models.BooleanField(default=True)),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=5, help_text='Example: 5 means 5%.', max_digits=5)),
                ('late_deduction_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('absent_deduction_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_setting', to='users.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StaffPermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('late', 'Come Late'), ('leave_early', 'Leave Early'), ('day_leave', 'Day Leave'), ('sick_leave', 'Sick Leave'), ('other', 'Other')], default='other', max_length=30)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('time_to', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('proof_photo', models.ImageField(blank=True, null=True, upload_to='staff_permissions/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_staff_permissions', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to='users.staffprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Shift', max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('late_after_minutes', models.PositiveIntegerField(default=10, help_text='Example: shift starts 8:00, late after 10 minutes means late from 8:11.')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_shifts', to='users.staffprofile')),
            ],
            options={
                'ordering': ['staff__user__username', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('leave', 'Leave'), ('permission', 'Permission'), ('half_day', 'Half Day')], default='present', max_length=30)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('scan_method', models.CharField(choices=[('branch_qr', 'Branch QR'), ('manual', 'Manual')], default='branch_qr', max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_from_branch_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('device_info', models.TextField(blank=True)),
                ('ip_address', models.CharField(blank=True, max_length=80)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicious_reason', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_attendances', to='inventory.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_attendances', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_attendances', to='users.staffprofile')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='staffs.staffshift')),
            ],
            options={
                'ordering': ['-date', 'staff__user__username'],
                'unique_together': {('staff', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StaffWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_work_day', models.BooleanField(default=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_days', to='users.staffprofile')),
            ],
            options={
                'ordering': ['staff__user__username', 'weekday'],
                'unique_together': {('staff', 'weekday')},
            },
        ),
    ]
