# Generated by Django 6.0.4 on 2026-07-07 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_itemvariant_options_itemvariant_sort_order_and_more'),
        ('pos', '0013_abapaymentsession_combinedpaymentsession'),
        ('staffs', '0001_initial'),
        ('users', '0002_alter_staffprofile_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroomingCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5, help_text='Example: 5 means 5% of grooming sale amount.', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='approved', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grooming_commissions', to='inventory.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grooming_commissions', to=settings.AUTH_USER_MODEL)),
                ('payroll_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grooming_commissions', to='staffs.payrollrecord')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grooming_commission', to='pos.sale')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grooming_commissions', to='users.staffprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
