# Generated by Django 6.0.4 on 2026-07-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_groomingcommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='allowed_day_off',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='attendance_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='day_off_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='dog_sale_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='grooming_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='over_day_off_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='pet_sale_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='pet_sale_target_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='unused_day_off_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='unused_day_off_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='used_day_off',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffpayrollsetting',
            name='allowed_day_off_per_month',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='staffpayrollsetting',
            name='allowed_late_times',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='staffpayrollsetting',
            name='grooming_commission_rate',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Grooming commission percentage. Example: 5 means 5%.', max_digits=5),
        ),
        migrations.AddField(
            model_name='staffpayrollsetting',
            name='no_late_bonus',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AddField(
            model_name='staffpayrollsetting',
            name='over_day_off_deduction_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='staffpayrollsetting',
            name='pet_sale_commission_rate',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Pet sale commission percentage. Example: 5 means 5%.', max_digits=5),
        ),
        migrations.AddField(
            model_name='staffpayrollsetting',
            name='unused_day_off_bonus_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
