# Generated by Django 6.0.4 on 2026-07-18 17:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_stockcountsession_stockcountline_and_more'),
        ('staffs', '0003_payrollrecord_allowed_day_off_and_more'),
        ('users', '0002_alter_staffprofile_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroomingWorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GroomingHelperWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(default=django.utils.timezone.localdate)),
                ('helper_name', models.CharField(default='Helper', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grooming_helper_work', to='inventory.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grooming_helper_work', to=settings.AUTH_USER_MODEL)),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='helper_records', to='staffs.groomingworktype')),
            ],
            options={
                'ordering': ['-work_date', 'work_type__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('bonus', 'Bonus'), ('deduction', 'Deduction'), ('advance', 'Salary Advance')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('record_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reason', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_adjustments', to=settings.AUTH_USER_MODEL)),
                ('payroll_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='staffs.payrollrecord')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_adjustments', to='users.staffprofile')),
            ],
            options={
                'ordering': ['-record_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffWorkCommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_type', models.CharField(choices=[('per_unit', 'Every unit × rate'), ('after_threshold', 'Only units after threshold × rate'), ('fixed_target', 'Reach target = fixed bonus'), ('per_block', 'Every completed block = fixed amount')], default='after_threshold', max_length=30)),
                ('threshold_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rate_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('block_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_commission_rules', to='users.staffprofile')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_commission_rules', to='staffs.groomingworktype')),
            ],
            options={
                'ordering': ['staff__user__username', 'work_type__sort_order', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='GroomingWorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(default=django.utils.timezone.localdate)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('locked', 'Locked in Payroll')], default='draft', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grooming_work_records', to='inventory.branch')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_grooming_work_records', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grooming_work_records', to=settings.AUTH_USER_MODEL)),
                ('payroll_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grooming_work_records', to='staffs.payrollrecord')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grooming_work_records', to='users.staffprofile')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_records', to='staffs.groomingworktype')),
            ],
            options={
                'ordering': ['-work_date', '-created_at'],
                'indexes': [models.Index(fields=['work_date', 'branch', 'status'], name='staffs_groo_work_da_36a937_idx'), models.Index(fields=['staff', 'work_date'], name='staffs_groo_staff_i_4fc461_idx')],
            },
        ),
        migrations.CreateModel(
            name='POSServiceWorkMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grooming_work_mappings', to='inventory.item')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_mappings', to='staffs.groomingworktype')),
            ],
            options={
                'ordering': ['item__name', 'work_type__sort_order', 'work_type__name'],
                'constraints': [models.UniqueConstraint(fields=('item', 'work_type'), name='unique_pos_item_work_type_mapping')],
            },
        ),
    ]
