# Generated by Django 6.0.4 on 2026-04-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_salepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
