# Generated by Django 6.0.4 on 2026-04-27 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_possetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('system_cash_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('system_cash_khr', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('system_aba_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('counted_cash_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('counted_cash_khr', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('counted_aba_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.TextField(blank=True, default='')),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
