# Generated by Django 6.0.4 on 2026-04-28 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_branch_branchstock'),
        ('pos', '0005_cashcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.branch'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.branch'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.itemvariant'),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('cash_usd', 'Cash USD'), ('cash_khr', 'Cash KHR'), ('aba', 'ABA'), ('aba_usd', 'ABA USD'), ('aba_khr', 'ABA KHR'), ('bank', 'Bank'), ('other', 'Other')], default='cash', max_length=20),
        ),
    ]
