# Generated by Django 6.0.4 on 2026-04-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_sale_branch_saleitem_branch_saleitem_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='delivery_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('walk_in', 'Walk-in'), ('prepare_delivery', 'Prepare for Delivery')], default='walk_in', max_length=30),
        ),
    ]
