# Generated by Django 6.0.4 on 2026-05-04 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_stockmovement_after_quantity_and_more'),
        ('pos', '0007_sale_delivery_created_sale_sale_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashcount',
            options={'ordering': ['-date', 'branch__name']},
        ),
        migrations.AddField(
            model_name='cashcount',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_counts', to='inventory.branch'),
        ),
        migrations.AlterField(
            model_name='cashcount',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='cashcount',
            unique_together={('branch', 'date')},
        ),
    ]
