# Generated by Django 6.0.4 on 2026-05-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_deliverycompany'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryCompany',
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_type',
            field=models.CharField(default='percent', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_type',
            field=models.CharField(default='percent', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
