# Generated by Django 6.0.4 on 2026-05-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_delete_deliverycompany_sale_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcount',
            name='expected_cash_khr',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='cashcount',
            name='opening_change_khr',
            field=models.DecimalField(decimal_places=0, default=100000, max_digits=14),
        ),
    ]
