# Generated by Django 6.0.4 on 2026-05-13 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_itemedithistory'),
        ('pos', '0011_cashcount_expected_cash_khr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashcount',
            name='counted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_counts_counted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BranchCashFloat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_change_khr', models.DecimalField(decimal_places=0, default=100000, max_digits=14)),
                ('note', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_float', to='inventory.branch')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_branch_cash_floats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['branch__name'],
            },
        ),
    ]
