# Generated by Django 6.0.4 on 2026-05-17 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_branch_allowed_radius_meters_branch_latitude_and_more'),
        ('pos', '0012_alter_cashcount_counted_by_branchcashfloat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ABAPaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=120, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('qr_text', models.TextField(blank=True, default='')),
                ('qr_image_url', models.URLField(blank=True, default='')),
                ('aba_tran_id', models.CharField(blank=True, default='', max_length=120)),
                ('aba_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aba_payment_sessions', to='inventory.branch')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aba_payment_sessions', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aba_payment_sessions', to='pos.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CombinedPaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_sale_id', models.PositiveIntegerField(blank=True, help_text='PetSale ID from pets app', null=True)),
                ('session_key', models.CharField(max_length=120, unique=True)),
                ('aba_tran_id', models.CharField(blank=True, default='', max_length=120)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pos_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pet_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='waiting', max_length=20)),
                ('qr_text', models.TextField(blank=True, default='')),
                ('qr_image_url', models.URLField(blank=True, default='')),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='combined_payment_sessions', to='inventory.branch')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pos_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combined_payment_sessions', to='pos.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
