# Generated by Django 6.0.4 on 2026-07-30 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_stockcountsession_stockcountline_and_more'),
        ('pos', '0013_abapaymentsession_combinedpaymentsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='DailyCashExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('grab', 'Grab'), ('vet', 'VET'), ('jt', 'J&T'), ('delivery', 'Other Delivery'), ('supplies', 'Shop Supplies'), ('refund', 'Customer Refund'), ('other', 'Other')], default='other', max_length=30)),
                ('source', models.CharField(choices=[('cash_usd', 'Cash USD'), ('cash_khr', 'Cash KHR'), ('aba_usd', 'ABA USD'), ('aba_khr', 'ABA KHR')], default='cash_usd', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_cash_expenses', to='inventory.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_cash_expenses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['branch', 'date'], name='pos_dailyca_branch__7b526e_idx')],
            },
        ),
    ]
