# Generated by Django 6.0.4 on 2026-05-06 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customerhistory'),
        ('pets', '0003_petsale_cancel_reason_petsale_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name='CustomerPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='customer_pets/')),
                ('pet_name', models.CharField(blank=True, max_length=120)),
                ('pet_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], default='dog', max_length=20)),
                ('breed', models.CharField(blank=True, max_length=120)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('color', models.CharField(blank=True, max_length=80)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('age_text', models.CharField(blank=True, max_length=80)),
                ('source', models.CharField(choices=[('bubu_sale', 'Bought at BUBU'), ('bubu_preorder', 'BUBU Pre-order'), ('customer_own', 'Customer Own Pet')], default='customer_own', max_length=30)),
                ('bought_date', models.DateField(blank=True, null=True)),
                ('warranty_start_date', models.DateField(blank=True, null=True)),
                ('warranty_expire_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_pets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='customers.customer')),
                ('pet_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_pet_profiles', to='pets.petsale')),
            ],
        ),
    ]
